### ISSUE TITLE
How does this integrate with the AssemblyScript memory allocator?

### ISSUE THREAD

**Issue by Heath123** [fabriciopashaj/as-malloc#2]
Does it allocate a page of memory to use as its own heap, or can it store things in the existing heap managed by the AssemblyScript runtime? I can’t really tell by looking at the source code

**Comment by fabricio-p** [comment]
It will try to work on a single memory page (the first one that is), that's why I say that you have to set `--memoryBase` to page size in bytes if you use a managed runtime. Not sure if it still works that way after v0.20.0 because I haven't touched AS in a long time
